// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: stream_response.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 流式请求：和普通请求没有区别
type StreamResponseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *StreamResponseRequest) Reset() {
	*x = StreamResponseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stream_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponseRequest) ProtoMessage() {}

func (x *StreamResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_stream_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponseRequest.ProtoReflect.Descriptor instead.
func (*StreamResponseRequest) Descriptor() ([]byte, []int) {
	return file_stream_response_proto_rawDescGZIP(), []int{0}
}

func (x *StreamResponseRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// 流式响应：和普通响应没有区别
type StreamResponseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *StreamResponseResponse) Reset() {
	*x = StreamResponseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stream_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamResponseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponseResponse) ProtoMessage() {}

func (x *StreamResponseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_stream_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponseResponse.ProtoReflect.Descriptor instead.
func (*StreamResponseResponse) Descriptor() ([]byte, []int) {
	return file_stream_response_proto_rawDescGZIP(), []int{1}
}

func (x *StreamResponseResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_stream_response_proto protoreflect.FileDescriptor

var file_stream_response_proto_rawDesc = []byte{
	0x0a, 0x15, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2b, 0x0a, 0x15, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x2c, 0x0a, 0x16, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x32, 0x59, 0x0a, 0x14, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x41, 0x0a, 0x0c, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x16, 0x2e, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_stream_response_proto_rawDescOnce sync.Once
	file_stream_response_proto_rawDescData = file_stream_response_proto_rawDesc
)

func file_stream_response_proto_rawDescGZIP() []byte {
	file_stream_response_proto_rawDescOnce.Do(func() {
		file_stream_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_stream_response_proto_rawDescData)
	})
	return file_stream_response_proto_rawDescData
}

var file_stream_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_stream_response_proto_goTypes = []interface{}{
	(*StreamResponseRequest)(nil),  // 0: StreamResponseRequest
	(*StreamResponseResponse)(nil), // 1: StreamResponseResponse
}
var file_stream_response_proto_depIdxs = []int32{
	0, // 0: StreamResponseServer.ServerStream:input_type -> StreamResponseRequest
	1, // 1: StreamResponseServer.ServerStream:output_type -> StreamResponseResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_stream_response_proto_init() }
func file_stream_response_proto_init() {
	if File_stream_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stream_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamResponseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_stream_response_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamResponseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stream_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_stream_response_proto_goTypes,
		DependencyIndexes: file_stream_response_proto_depIdxs,
		MessageInfos:      file_stream_response_proto_msgTypes,
	}.Build()
	File_stream_response_proto = out.File
	file_stream_response_proto_rawDesc = nil
	file_stream_response_proto_goTypes = nil
	file_stream_response_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StreamResponseServerClient is the client API for StreamResponseServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StreamResponseServerClient interface {
	// 服务端流模式
	ServerStream(ctx context.Context, in *StreamResponseRequest, opts ...grpc.CallOption) (StreamResponseServer_ServerStreamClient, error)
}

type streamResponseServerClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamResponseServerClient(cc grpc.ClientConnInterface) StreamResponseServerClient {
	return &streamResponseServerClient{cc}
}

func (c *streamResponseServerClient) ServerStream(ctx context.Context, in *StreamResponseRequest, opts ...grpc.CallOption) (StreamResponseServer_ServerStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_StreamResponseServer_serviceDesc.Streams[0], "/StreamResponseServer/ServerStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &streamResponseServerServerStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type StreamResponseServer_ServerStreamClient interface {
	Recv() (*StreamResponseResponse, error)
	grpc.ClientStream
}

type streamResponseServerServerStreamClient struct {
	grpc.ClientStream
}

func (x *streamResponseServerServerStreamClient) Recv() (*StreamResponseResponse, error) {
	m := new(StreamResponseResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamResponseServerServer is the server API for StreamResponseServer service.
type StreamResponseServerServer interface {
	// 服务端流模式
	ServerStream(*StreamResponseRequest, StreamResponseServer_ServerStreamServer) error
}

// UnimplementedStreamResponseServerServer can be embedded to have forward compatible implementations.
type UnimplementedStreamResponseServerServer struct {
}

func (*UnimplementedStreamResponseServerServer) ServerStream(*StreamResponseRequest, StreamResponseServer_ServerStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ServerStream not implemented")
}

func RegisterStreamResponseServerServer(s *grpc.Server, srv StreamResponseServerServer) {
	s.RegisterService(&_StreamResponseServer_serviceDesc, srv)
}

func _StreamResponseServer_ServerStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamResponseRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamResponseServerServer).ServerStream(m, &streamResponseServerServerStreamServer{stream})
}

type StreamResponseServer_ServerStreamServer interface {
	Send(*StreamResponseResponse) error
	grpc.ServerStream
}

type streamResponseServerServerStreamServer struct {
	grpc.ServerStream
}

func (x *streamResponseServerServerStreamServer) Send(m *StreamResponseResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _StreamResponseServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "StreamResponseServer",
	HandlerType: (*StreamResponseServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ServerStream",
			Handler:       _StreamResponseServer_ServerStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "stream_response.proto",
}
